on:
  push:
    branches:
      - master

name: Deploy Cloudflare Workers
jobs:
  builddeploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        root-project-path: [./]
    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ${{ matrix.root-project-path }}
      run: yarn install
    - name: Register .env
      working-directory: ${{ matrix.root-project-path }}
      env:
        NEXT_PUBLIC_API_ROOT_URL: ${{ secrets.NEXT_PUBLIC_API_ROOT_URL }}
      run: |
        echo "NEXT_PUBLIC_API_ROOT_URL=${NEXT_PUBLIC_API_ROOT_URL}" >> ./.env
    - name: Next.js build
      working-directory: ${{ matrix.root-project-path }}
      run: yarn run build
    - name: deploy to cloudflare workers
      uses: cloudflare/wrangler-action@v3
      with:
        workingDirectory: ${{ matrix.root-project-path }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}